# TODO: Sync this back to andreijiroh-dev/.github repo soon :)
github: ajhalili2006
ko_fi: ajhalili2006
patreon: ajhalili2006
liberapay: ajhalili2006
buy_me_a_coffee: ajhalili2006
open_collective: andreijiroh-dev
custom:
  - https://paypal.me/ajhalili2006
  - https://sponsors.andreijiroh.dev
  - https:/recaptime.dev/donate