# The Docker image that will be used to build your app
image:
  name: dock.mau.dev/andreijiroh-dev/docker-images/mkdocs-material:latest
  entrypoint: ["/bin/bash", "-l", "-c"] # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/2109#note_47480476

stages:
  - test
  - build

default:
  tags:
    - amd64 # currently, we only the image in amd64 right now.
  # Functions that should be executed before the build script is run
  before_script:
    - pipenv install --ignore-pipfile --deploy
    - npm ci
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ssh-agent > /tmp/.ssh-agent.env

# Global builds and stuff
variables:
  DEBUG: "1" # MAY HORRIBLY LEAK SECRETS, PROCEED WITH CAUTION
  FF_ENABLE_COMMIT_DATA: "true"
  FF_GENERATE_SOCIAL_CARDS: "true"
  SECURE_FILES_DOWNLOAD_PATH: .secretskit
  GIT_DEPTH: "0"
  DOTENV_PRIVATE_KEY: $DOTENV_PRIVATE_KEY_CI

pages:
  stage: build
  script:
    - |
      source /tmp/.ssh-agent.env
      ./bin/build.sh
      ./bin/deploy.sh
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  variables:
    CF_PAGES_PROJECT_NAME: ajhalili2006
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
